/**
 * Image Validation Layer
 *
 * First gate in the scan pipeline.  Determines whether a captured or
 * uploaded image is:
 *   a) A recognisable H₂S dosimeter/wristband image  → VALID_DOSIMETER
 *   b) A poor-quality capture (blur, glare, dark)      → GLARE_DETECTED / PLEASE_RESCAN
 *   c) A random / out-of-context image                 → INVALID_IMAGE / PATCH_NOT_DETECTED
 *
 * For real camera / upload images the layer now runs two sub-systems:
 *   1. StripDetectionEngine — canvas colour analysis to distinguish dosimeter
 *      strips from random images (80 % accuracy; swap point for TF.js model).
 *   2. OcrEngine — Tesseract.js to extract a printed demo code if present.
 *
 * For SVG internal demo images generated by the app itself the detection is
 * still done via the embedded `<!-- demo-code:XXX -->` HTML comment (fast,
 * zero-latency, 100 % reliable for in-app flows).
 *
 * ─── Production replacement ────────────────────────────────────────────────
 * Replace `validateRealImage()` with a call to a real CV model API:
 *
 *   const response = await fetch('/api/analyse', {
 *     method: 'POST',
 *     body: JSON.stringify({ image: dataUrl }),
 *   });
 *   const { isValid, demoCode, rejectionReason } = await response.json();
 *
 * Everything else in this file (types, SVG path, embedDemoCode) stays intact.
 * ────────────────────────────────────────────────────────────────────────────
 */

import { detectStrip } from './strip-detection-engine';
import { extractCodeFromImage } from './ocr-engine';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ImageValidationStatus =
  | 'VALID_DOSIMETER'        // Looks like a dosimeter → proceed to analysis
  | 'INVALID_IMAGE'          // Cannot be analysed at all
  | 'GLARE_DETECTED'         // Too much specular reflection / overexposed
  | 'PATCH_NOT_DETECTED'     // Colour-patch grid not visible in expected region
  | 'PLEASE_RESCAN';         // Unclassified but unsuitable (dark, blank, etc.)

export interface ImageValidationResult {
  status: ImageValidationStatus;
  /** Human-readable rejection reason; null when VALID */
  rejectionReason: string | null;
  /** Extracted demo code (e.g. "H01") when found by OCR or SVG sentinel */
  demoCode: string | null;
  /** Confidence in the validation decision, 0–1 */
  confidence: number;
  /**
   * Strip detection diagnostics (null for SVG/internal images).
   * Useful for debugging and future calibration threshold tuning.
   */
  stripDiagnostics?: {
    meanL: number; meanA: number; meanB: number;
    colourEntropy: number; dosimeterHueFraction: number;
  } | null;
}

// ---------------------------------------------------------------------------
// SVG / internal demo-image constants
// ---------------------------------------------------------------------------

const DEMO_CODE_PATTERN = /demo-code:([A-Z]\d{2})/;
const DOSIMETER_SENTINEL = /H2S[\s_-]?SENSOR/i;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Validate an image before processing.
 *
 * @param imageDataUrl  - data-URI (data:image/...) from camera, file upload,
 *                        or an SVG data-URI generated internally.
 * @param isInternalDemo - Pass `true` when the image was generated by the app
 *                         itself (e.g. getScenarioBadgeImage) rather than
 *                         captured/uploaded by the user.  Skips heavy analysis.
 *
 * The function is async because OCR and canvas pixel-sampling are async.
 * For internal SVGs the fast synchronous path is taken immediately.
 */
export async function validateImage(
  imageDataUrl: string | null | undefined,
  isInternalDemo = false,
): Promise<ImageValidationResult> {
  // No image at all
  if (!imageDataUrl) {
    return {
      status: 'INVALID_IMAGE',
      rejectionReason: 'No image provided.',
      demoCode: null,
      confidence: 1,
      stripDiagnostics: null,
    };
  }

  // ── Fast path: internal SVG demo images ──────────────────────────────────
  if (isInternalDemo || imageDataUrl.startsWith('data:image/svg+xml')) {
    return validateSvgDemoImage(imageDataUrl);
  }

  // ── Real camera / upload images ───────────────────────────────────────────
  return validateRealImage(imageDataUrl);
}

// ---------------------------------------------------------------------------
// SVG path (fast, synchronous-equivalent)
// ---------------------------------------------------------------------------

function validateSvgDemoImage(dataUrl: string): ImageValidationResult {
  let svgText = dataUrl;
  try {
    const raw = dataUrl.replace(/^data:image\/svg\+xml[^,]*,/, '');
    svgText = decodeURIComponent(raw);
  } catch { /* keep as-is */ }

  const codeMatch = svgText.match(DEMO_CODE_PATTERN);
  const demoCode = codeMatch ? codeMatch[1] : null;
  const hasSentinel = DOSIMETER_SENTINEL.test(svgText);

  if (hasSentinel || demoCode) {
    return {
      status: 'VALID_DOSIMETER',
      rejectionReason: null,
      demoCode,
      confidence: 0.98,
      stripDiagnostics: null,
    };
  }

  return {
    status: 'INVALID_IMAGE',
    rejectionReason: 'Image does not appear to be an H₂S dosimeter.',
    demoCode: null,
    confidence: 0.85,
    stripDiagnostics: null,
  };
}

// ---------------------------------------------------------------------------
// Real-image path
// ---------------------------------------------------------------------------

/**
 * ⚙ SCOPE: Replace this function body with a real CV model API call when
 * ready.  The function signature and return type stay the same.
 */
async function validateRealImage(dataUrl: string): Promise<ImageValidationResult> {
  // ── Format check ─────────────────────────────────────────────────────────
  const isJpegOrPng =
    dataUrl.startsWith('data:image/jpeg;base64,') ||
    dataUrl.startsWith('data:image/png;base64,') ||
    dataUrl.startsWith('data:image/webp;base64,');

  if (!isJpegOrPng) {
    return {
      status: 'INVALID_IMAGE',
      rejectionReason: 'Unrecognised image format. Please capture with the camera.',
      demoCode: null,
      confidence: 0.95,
      stripDiagnostics: null,
    };
  }

  // ── Payload size guard ───────────────────────────────────────────────────
  const base64 = dataUrl.split(',')[1] ?? '';
  const approxBytes = base64.length * 0.75;

  if (approxBytes < 5_000) {
    return {
      status: 'PLEASE_RESCAN',
      rejectionReason: 'Image appears blank or corrupted. Please re-scan.',
      demoCode: null,
      confidence: 0.88,
      stripDiagnostics: null,
    };
  }

  if (approxBytes > 2_500_000) {
    return {
      status: 'GLARE_DETECTED',
      rejectionReason: 'Excessive glare detected. Move to diffuse lighting and re-scan.',
      demoCode: null,
      confidence: 0.72,
      stripDiagnostics: null,
    };
  }

  // ── Strip detection (colour heuristics / future TF.js) ───────────────────
  let stripResult: Awaited<ReturnType<typeof detectStrip>> | null = null;
  try {
    stripResult = await detectStrip(dataUrl);
  } catch {
    // If detection fails (e.g. SSR context), continue optimistically
    stripResult = null;
  }

  if (stripResult && !stripResult.isStrip) {
    // Map rejection reason to the appropriate status
    const reason = stripResult.rejectionReason ?? 'Dosimeter not detected.';
    const isDark = stripResult.diagnostics.meanL < 25;
    const status: ImageValidationStatus = isDark ? 'PLEASE_RESCAN' : 'PATCH_NOT_DETECTED';
    return {
      status,
      rejectionReason: reason,
      demoCode: null,
      confidence: stripResult.confidence,
      stripDiagnostics: stripResult.diagnostics,
    };
  }

  // ── OCR: attempt to read a printed demo code ──────────────────────────────
  // This runs in parallel-friendly fashion; failure is non-fatal.
  let ocrCode: string | null = null;
  try {
    const ocr = await extractCodeFromImage(dataUrl);
    ocrCode = ocr.code;
  } catch {
    ocrCode = null;
  }

  return {
    status: 'VALID_DOSIMETER',
    rejectionReason: null,
    demoCode: ocrCode,
    confidence: stripResult ? stripResult.confidence : 0.70,
    stripDiagnostics: stripResult?.diagnostics ?? null,
  };
}

// ---------------------------------------------------------------------------
// Utility: embed demo code in SVG data-URI
// ---------------------------------------------------------------------------

/**
 * Inject a demo code comment into an SVG data-URI so the validation layer
 * can detect it when the image passes through `validateImage()`.
 *
 * Usage:
 *   const uri = embedDemoCode(rawSvgDataUri, 'H01');
 */
export function embedDemoCode(svgDataUri: string, code: string): string {
  try {
    const prefix = svgDataUri.match(/^data:image\/svg\+xml[^,]*,/)?.[0] ?? '';
    const raw = svgDataUri.slice(prefix.length);
    const decoded = decodeURIComponent(raw);
    const injected = decoded.replace(
      '</svg>',
      `<!-- demo-code:${code} --></svg>`,
    );
    return `${prefix}${encodeURIComponent(injected)}`;
  } catch {
    return svgDataUri;
  }
}
